import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import NavigationSidebar from "@/component/sidebar";
import SidebarWrapper from "@/component/sidebarWrapper";
import MainContentWrapper from "@/component/MainContentWrapper";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "MonitorX",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ToastContainer
          position="top-center"
          autoClose={2500}
          hideProgressBar
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          className={`font-bold scale-75 custom-toast-container`}
        />
        <div className="flex">
          {/* Fixed Sidebar */}
          <div className="fixed top-0 left-0 h-screen w-68 text-white p-4">
            <SidebarWrapper/>
          </div>

          {/* Main Content */}
          <MainContentWrapper>{children}</MainContentWrapper>
        </div>
      </body>
    </html>
  );
}
