import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

const inter =  Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "MonitorX",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ToastContainer
          position="top-right"
          autoClose={2500}
          hideProgressBar
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          className={`font-bold scale-75`}
        />
        {children}
      </body>
    </html>
  );
}
